# Generated by Django 4.1.13 on 2024-11-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('job_role', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('date_received', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
